project_name: autobot

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

builds:
  -
    id: autobot
    binary: autobot
    main: server/main.go
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X github.com/andersnormal/autobot/server/cmd.build={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386

release:
  draft: false

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "autobot_checksums.txt"

archives:
  -
    id: autobot
    builds:
    - autobot
    name_template: "autobot_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  -
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    binaries:
      - autobot
    image_templates:
     - "andersnormal/{{.ProjectName}}:latest"
     - "andersnormal/{{.ProjectName}}:{{ .Tag }}"
     - "andersnormal/{{.ProjectName}}"
