language: go

matrix:
  include:
  - go: 1.11.x
  - go: 1.12.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip

addons:
  apt:
    packages:
    - rpm

script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

services:
  - docker

notifications:
  slack:
    rooms:
      secure: b0F0ai7/cD9bmnJWTGc9sl4xvR3tpDa5PFo8p8CN7tO9rs0VcpN8x89VU3+xbcv2E/uI1SnWsNBDlwItVRBm83ZLtW+CtmP4StV4f981eG1qgJkdPHlgD5AkUcz+bsa5Ot+Rkmmku0yU+n0XUvrQlEN7xtiGfxVpopsRsvb80fwltvAoD3rVg0QDBB/DawE+4l4TvLmKsdRRIx7Va8DXp4iGLI9EzRQx/pXOPwHrx7n4CjzZjutOdKqnfNVq4x0bbNY7/z4xnWlc9zEEX9YhqW1UJEV+v0VvXmirAU+LCbHSwlsOR20RczWg2qkA8fnYZPpBQ6NY5LzBYRSaKnWYKjAlTh47dlaKuaT81+rOZhUewFd62WJ+zl1tk2MJkDDimq3N4SrcdOwLzpbRUE63yX1EHO1gSuisgD5wsjrrtj73xRjJLjnGB6WKydA3TIDmOtLjdY7ExR9mD2DrFg9VCIz45879ftbK3Lv978xAEQIa67PrGs01fLlR6rPHbPAz4TebVGGALdnIWWeswd5KEiSyi2jsve/uQqR1TJlIOM47l2/QB1UKPN+Z4y11Cyn+2+Kqblzzlau18HyJERjiYpbtZRENAaD/6O7W3WhbBp1lhUU0jDHRRNixSvIXvxAStd30iK1bQ4wYRUmSts+0j1ibSOdMRERAaFJvDderd/o=

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
