// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Errors to occur in the communication
type PluginError_Code int32

const (
	PluginError_UNKNOWN PluginError_Code = 0
)

var PluginError_Code_name = map[int32]string{
	0: "UNKNOWN",
}

var PluginError_Code_value = map[string]int32{
	"UNKNOWN": 0,
}

func (x PluginError_Code) String() string {
	return proto.EnumName(PluginError_Code_name, int32(x))
}

func (PluginError_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{8, 0}
}

// Plugin ...
type Plugin struct {
	// meta ...
	Meta                 *Plugin_Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetMeta() *Plugin_Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

// Meta ...
type Plugin_Meta struct {
	// name ...
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// identifier ...
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// version ...
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// path ...
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin_Meta) Reset()         { *m = Plugin_Meta{} }
func (m *Plugin_Meta) String() string { return proto.CompactTextString(m) }
func (*Plugin_Meta) ProtoMessage()    {}
func (*Plugin_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0, 0}
}

func (m *Plugin_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin_Meta.Unmarshal(m, b)
}
func (m *Plugin_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin_Meta.Marshal(b, m, deterministic)
}
func (m *Plugin_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin_Meta.Merge(m, src)
}
func (m *Plugin_Meta) XXX_Size() int {
	return xxx_messageInfo_Plugin_Meta.Size(m)
}
func (m *Plugin_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin_Meta proto.InternalMessageInfo

func (m *Plugin_Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin_Meta) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Plugin_Meta) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Plugin_Meta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Event ...
type Event struct {
	// Types that are valid to be assigned to Event:
	//	*Event_Reply
	//	*Event_Message
	Event                isEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Reply struct {
	Reply *Reply `protobuf:"bytes,10,opt,name=reply,proto3,oneof"`
}

type Event_Message struct {
	Message *Message `protobuf:"bytes,11,opt,name=message,proto3,oneof"`
}

func (*Event_Reply) isEvent_Event() {}

func (*Event_Message) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetReply() *Reply {
	if x, ok := m.GetEvent().(*Event_Reply); ok {
		return x.Reply
	}
	return nil
}

func (m *Event) GetMessage() *Message {
	if x, ok := m.GetEvent().(*Event_Message); ok {
		return x.Message
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Reply)(nil),
		(*Event_Message)(nil),
	}
}

// Message ...
type Message struct {
	// Types that are valid to be assigned to Message:
	//	*Message_TextMessage
	Message              isMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Message interface {
	isMessage_Message()
}

type Message_TextMessage struct {
	TextMessage *TextMessage `protobuf:"bytes,1,opt,name=text_message,json=textMessage,proto3,oneof"`
}

func (*Message_TextMessage) isMessage_Message() {}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetTextMessage() *TextMessage {
	if x, ok := m.GetMessage().(*Message_TextMessage); ok {
		return x.TextMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_TextMessage)(nil),
	}
}

// Reply ...
type Reply struct {
	// Types that are valid to be assigned to Reply:
	//	*Reply_TextMessage
	Reply                isReply_Reply `protobuf_oneof:"reply"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

type isReply_Reply interface {
	isReply_Reply()
}

type Reply_TextMessage struct {
	TextMessage *TextMessage `protobuf:"bytes,1,opt,name=text_message,json=textMessage,proto3,oneof"`
}

func (*Reply_TextMessage) isReply_Reply() {}

func (m *Reply) GetReply() isReply_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *Reply) GetTextMessage() *TextMessage {
	if x, ok := m.GetReply().(*Reply_TextMessage); ok {
		return x.TextMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Reply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Reply_TextMessage)(nil),
	}
}

// TextMessage ...
type TextMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextMessage) Reset()         { *m = TextMessage{} }
func (m *TextMessage) String() string { return proto.CompactTextString(m) }
func (*TextMessage) ProtoMessage()    {}
func (*TextMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4}
}

func (m *TextMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextMessage.Unmarshal(m, b)
}
func (m *TextMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextMessage.Marshal(b, m, deterministic)
}
func (m *TextMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextMessage.Merge(m, src)
}
func (m *TextMessage) XXX_Size() int {
	return xxx_messageInfo_TextMessage.Size(m)
}
func (m *TextMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TextMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TextMessage proto.InternalMessageInfo

// Register ...
type Register struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register) Reset()         { *m = Register{} }
func (m *Register) String() string { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()    {}
func (*Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5}
}

func (m *Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register.Unmarshal(m, b)
}
func (m *Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register.Marshal(b, m, deterministic)
}
func (m *Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register.Merge(m, src)
}
func (m *Register) XXX_Size() int {
	return xxx_messageInfo_Register.Size(m)
}
func (m *Register) XXX_DiscardUnknown() {
	xxx_messageInfo_Register.DiscardUnknown(m)
}

var xxx_messageInfo_Register proto.InternalMessageInfo

type Register_Request struct {
	Topic                *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register_Request) Reset()         { *m = Register_Request{} }
func (m *Register_Request) String() string { return proto.CompactTextString(m) }
func (*Register_Request) ProtoMessage()    {}
func (*Register_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5, 0}
}

func (m *Register_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register_Request.Unmarshal(m, b)
}
func (m *Register_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register_Request.Marshal(b, m, deterministic)
}
func (m *Register_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register_Request.Merge(m, src)
}
func (m *Register_Request) XXX_Size() int {
	return xxx_messageInfo_Register_Request.Size(m)
}
func (m *Register_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Register_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Register_Request proto.InternalMessageInfo

func (m *Register_Request) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

type Register_Response struct {
	Plugin               *Plugin  `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Register_Response) Reset()         { *m = Register_Response{} }
func (m *Register_Response) String() string { return proto.CompactTextString(m) }
func (*Register_Response) ProtoMessage()    {}
func (*Register_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5, 1}
}

func (m *Register_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Register_Response.Unmarshal(m, b)
}
func (m *Register_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Register_Response.Marshal(b, m, deterministic)
}
func (m *Register_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Register_Response.Merge(m, src)
}
func (m *Register_Response) XXX_Size() int {
	return xxx_messageInfo_Register_Response.Size(m)
}
func (m *Register_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Register_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Register_Response proto.InternalMessageInfo

func (m *Register_Response) GetPlugin() *Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

// Unregister ...
type Unregister struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unregister) Reset()         { *m = Unregister{} }
func (m *Unregister) String() string { return proto.CompactTextString(m) }
func (*Unregister) ProtoMessage()    {}
func (*Unregister) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6}
}

func (m *Unregister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unregister.Unmarshal(m, b)
}
func (m *Unregister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unregister.Marshal(b, m, deterministic)
}
func (m *Unregister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unregister.Merge(m, src)
}
func (m *Unregister) XXX_Size() int {
	return xxx_messageInfo_Unregister.Size(m)
}
func (m *Unregister) XXX_DiscardUnknown() {
	xxx_messageInfo_Unregister.DiscardUnknown(m)
}

var xxx_messageInfo_Unregister proto.InternalMessageInfo

type Unregister_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unregister_Request) Reset()         { *m = Unregister_Request{} }
func (m *Unregister_Request) String() string { return proto.CompactTextString(m) }
func (*Unregister_Request) ProtoMessage()    {}
func (*Unregister_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6, 0}
}

func (m *Unregister_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unregister_Request.Unmarshal(m, b)
}
func (m *Unregister_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unregister_Request.Marshal(b, m, deterministic)
}
func (m *Unregister_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unregister_Request.Merge(m, src)
}
func (m *Unregister_Request) XXX_Size() int {
	return xxx_messageInfo_Unregister_Request.Size(m)
}
func (m *Unregister_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Unregister_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Unregister_Request proto.InternalMessageInfo

type Unregister_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unregister_Response) Reset()         { *m = Unregister_Response{} }
func (m *Unregister_Response) String() string { return proto.CompactTextString(m) }
func (*Unregister_Response) ProtoMessage()    {}
func (*Unregister_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6, 1}
}

func (m *Unregister_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unregister_Response.Unmarshal(m, b)
}
func (m *Unregister_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unregister_Response.Marshal(b, m, deterministic)
}
func (m *Unregister_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unregister_Response.Merge(m, src)
}
func (m *Unregister_Response) XXX_Size() int {
	return xxx_messageInfo_Unregister_Response.Size(m)
}
func (m *Unregister_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Unregister_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Unregister_Response proto.InternalMessageInfo

// Topic ...
type Topic struct {
	ClusterUrl           string   `protobuf:"bytes,1,opt,name=cluster_url,json=clusterUrl,proto3" json:"cluster_url,omitempty"`
	ClusterId            string   `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{7}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetClusterUrl() string {
	if m != nil {
		return m.ClusterUrl
	}
	return ""
}

func (m *Topic) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// PluginError
//
// These are standard error codes.
type PluginError struct {
	Code                 PluginError_Code `protobuf:"varint,1,opt,name=code,proto3,enum=proto.PluginError_Code" json:"code,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PluginError) Reset()         { *m = PluginError{} }
func (m *PluginError) String() string { return proto.CompactTextString(m) }
func (*PluginError) ProtoMessage()    {}
func (*PluginError) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{8}
}

func (m *PluginError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginError.Unmarshal(m, b)
}
func (m *PluginError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginError.Marshal(b, m, deterministic)
}
func (m *PluginError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginError.Merge(m, src)
}
func (m *PluginError) XXX_Size() int {
	return xxx_messageInfo_PluginError.Size(m)
}
func (m *PluginError) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginError.DiscardUnknown(m)
}

var xxx_messageInfo_PluginError proto.InternalMessageInfo

func (m *PluginError) GetCode() PluginError_Code {
	if m != nil {
		return m.Code
	}
	return PluginError_UNKNOWN
}

func (m *PluginError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.PluginError_Code", PluginError_Code_name, PluginError_Code_value)
	proto.RegisterType((*Plugin)(nil), "proto.Plugin")
	proto.RegisterType((*Plugin_Meta)(nil), "proto.Plugin.Meta")
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Reply)(nil), "proto.Reply")
	proto.RegisterType((*TextMessage)(nil), "proto.TextMessage")
	proto.RegisterType((*Register)(nil), "proto.Register")
	proto.RegisterType((*Register_Request)(nil), "proto.Register.Request")
	proto.RegisterType((*Register_Response)(nil), "proto.Register.Response")
	proto.RegisterType((*Unregister)(nil), "proto.Unregister")
	proto.RegisterType((*Unregister_Request)(nil), "proto.Unregister.Request")
	proto.RegisterType((*Unregister_Response)(nil), "proto.Unregister.Response")
	proto.RegisterType((*Topic)(nil), "proto.Topic")
	proto.RegisterType((*PluginError)(nil), "proto.PluginError")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x4d, 0xa8, 0x1d, 0x93, 0x71, 0x5a, 0xa1, 0xe1, 0x50, 0x63, 0x89, 0x0f, 0x2d, 0x1f, 0x42,
	0x20, 0x2c, 0x11, 0x0e, 0x9c, 0x38, 0xd0, 0xaa, 0x52, 0x2b, 0x94, 0x80, 0x56, 0x8d, 0x38, 0x70,
	0x88, 0xdc, 0x78, 0x48, 0x57, 0x72, 0x6c, 0xb3, 0xde, 0x54, 0xe5, 0x47, 0xf0, 0x07, 0xf8, 0xb5,
	0x68, 0xbf, 0xec, 0x44, 0x70, 0xe2, 0xe4, 0x9d, 0xf7, 0xde, 0xbe, 0x19, 0xbf, 0x1d, 0x98, 0x34,
	0xe5, 0x76, 0x2d, 0xaa, 0xac, 0x91, 0xb5, 0xaa, 0x31, 0x34, 0x1f, 0xf6, 0x7b, 0x08, 0xa3, 0x2f,
	0x06, 0xc7, 0x17, 0x10, 0x6c, 0x48, 0xe5, 0xc9, 0xf0, 0xc9, 0xf0, 0x65, 0x3c, 0x45, 0xab, 0xcb,
	0x2c, 0x99, 0xcd, 0x48, 0xe5, 0xdc, 0xf0, 0xe9, 0x35, 0x04, 0xba, 0x42, 0x84, 0xa0, 0xca, 0x37,
	0x64, 0xf4, 0x63, 0x6e, 0xce, 0xf8, 0x08, 0x40, 0x14, 0x54, 0x29, 0xf1, 0x5d, 0x90, 0x4c, 0xee,
	0x18, 0x66, 0x07, 0xc1, 0x04, 0xa2, 0x1b, 0x92, 0xad, 0xa8, 0xab, 0xe4, 0xc0, 0x90, 0xbe, 0xd4,
	0x6e, 0x4d, 0xae, 0xae, 0x93, 0xc0, 0xba, 0xe9, 0x33, 0xbb, 0x82, 0xf0, 0xec, 0x86, 0x2a, 0x85,
	0xcf, 0x20, 0x94, 0xd4, 0x94, 0x3f, 0x13, 0x30, 0xb3, 0x4d, 0xdc, 0x6c, 0x5c, 0x63, 0xe7, 0x03,
	0x6e, 0x49, 0x7c, 0x05, 0xd1, 0x86, 0xda, 0x36, 0x5f, 0x53, 0x12, 0x1b, 0xdd, 0x91, 0xd3, 0xcd,
	0x2c, 0x7a, 0x3e, 0xe0, 0x5e, 0x70, 0x12, 0x41, 0x48, 0xda, 0x9a, 0xcd, 0x20, 0x72, 0x34, 0xbe,
	0x87, 0x89, 0xa2, 0x5b, 0xb5, 0xf4, 0x26, 0xfb, 0x41, 0x5c, 0xd2, 0xad, 0xea, 0x8d, 0x62, 0xd5,
	0x97, 0x27, 0xe3, 0xae, 0x31, 0xbb, 0x80, 0xd0, 0x4c, 0xf5, 0xff, 0x66, 0x91, 0xfb, 0x57, 0x76,
	0x08, 0xf1, 0x8e, 0x8c, 0x95, 0x70, 0x97, 0xd3, 0x5a, 0xb4, 0x8a, 0x64, 0xfa, 0x06, 0x22, 0x4e,
	0x3f, 0xb6, 0xd4, 0x2a, 0x64, 0x10, 0xaa, 0xba, 0x11, 0x2b, 0xd7, 0xc0, 0x47, 0x73, 0xa9, 0x31,
	0x6e, 0xa9, 0xf4, 0xad, 0xbe, 0xda, 0x36, 0x75, 0xd5, 0x12, 0x3e, 0x87, 0x91, 0xdd, 0x03, 0x77,
	0xe1, 0x70, 0xef, 0x9d, 0xb9, 0x23, 0xd9, 0x53, 0x80, 0x45, 0x25, 0x7d, 0xbf, 0x71, 0xd7, 0x2f,
	0x85, 0xde, 0x8b, 0x7d, 0x83, 0xd0, 0xf4, 0xc1, 0xc7, 0x10, 0xaf, 0xca, 0xad, 0x96, 0x2e, 0xb7,
	0xb2, 0x74, 0x1b, 0x01, 0x0e, 0x5a, 0xc8, 0x12, 0x1f, 0x82, 0xaf, 0x96, 0xa2, 0x70, 0x7b, 0x31,
	0x76, 0xc8, 0x45, 0xd1, 0xad, 0xd2, 0x41, 0xbf, 0x4a, 0x4c, 0x40, 0x6c, 0x67, 0x3a, 0x93, 0xb2,
	0x96, 0xf8, 0x1a, 0x82, 0x55, 0x5d, 0xd8, 0x1c, 0x8f, 0xa6, 0xc7, 0x7b, 0x53, 0x1b, 0x45, 0x76,
	0x5a, 0x17, 0xc4, 0x8d, 0x48, 0xaf, 0x99, 0xcf, 0xdd, 0xf6, 0xea, 0xde, 0xe7, 0x3e, 0x04, 0x5a,
	0x87, 0x31, 0x44, 0x8b, 0xf9, 0xa7, 0xf9, 0xe7, 0xaf, 0xf3, 0x7b, 0x83, 0xe9, 0xaf, 0x21, 0x44,
	0x1f, 0x8b, 0xbc, 0x51, 0x24, 0xf1, 0x43, 0x1f, 0x33, 0x1e, 0x77, 0x7b, 0x66, 0x81, 0xcc, 0x87,
	0x90, 0xfc, 0x4d, 0xb8, 0x78, 0x4f, 0x77, 0x73, 0xc3, 0x07, 0x4e, 0xd7, 0x43, 0x9d, 0x45, 0xfa,
	0x2f, 0xca, 0x9a, 0x5c, 0x8d, 0x0c, 0xf5, 0xee, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0xcd,
	0x6f, 0x78, 0xb2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdapterClient is the client API for Adapter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdapterClient interface {
	// Register ...
	Register(ctx context.Context, in *Register_Request, opts ...grpc.CallOption) (*Register_Response, error)
	// Unregister ...
	Unregister(ctx context.Context, in *Unregister_Request, opts ...grpc.CallOption) (*Unregister_Response, error)
}

type adapterClient struct {
	cc *grpc.ClientConn
}

func NewAdapterClient(cc *grpc.ClientConn) AdapterClient {
	return &adapterClient{cc}
}

func (c *adapterClient) Register(ctx context.Context, in *Register_Request, opts ...grpc.CallOption) (*Register_Response, error) {
	out := new(Register_Response)
	err := c.cc.Invoke(ctx, "/proto.Adapter/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterClient) Unregister(ctx context.Context, in *Unregister_Request, opts ...grpc.CallOption) (*Unregister_Response, error) {
	out := new(Unregister_Response)
	err := c.cc.Invoke(ctx, "/proto.Adapter/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterServer is the server API for Adapter service.
type AdapterServer interface {
	// Register ...
	Register(context.Context, *Register_Request) (*Register_Response, error)
	// Unregister ...
	Unregister(context.Context, *Unregister_Request) (*Unregister_Response, error)
}

func RegisterAdapterServer(s *grpc.Server, srv AdapterServer) {
	s.RegisterService(&_Adapter_serviceDesc, srv)
}

func _Adapter_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Register_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Adapter/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Register(ctx, req.(*Register_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adapter_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Unregister_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Adapter/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterServer).Unregister(ctx, req.(*Unregister_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Adapter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Adapter",
	HandlerType: (*AdapterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Adapter_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _Adapter_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
